name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-16.20.0-chrome-113.0.5672.92
      options: --user 1001  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: npm install  

      - name: Run Cypress tests
        run: npx cypress run --browser chrome 
