name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Cypress Docker image
        run: |
          docker build -t xyz-bank-e2e-tests .

      - name: Run Cypress tests
        run: |
          mkdir -p cypress/reports
          docker run --rm \
            -v $PWD:/e2e \
            -v $PWD/cypress/reports:/e2e/cypress/reports \
            -w /e2e \
            xyz-bank-e2e-tests

      - name: Archive Cypress test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-reports
          path: cypress/reports
